# Visit https://keel.notaku.site/documentation/environment-variables-and-secrets for more
# information about environment variables and secrets
environment:
  default:
  development:
  test:
  staging:
  production:

secrets:
